replicaCount: 3
maxUnavailable: 1
image:
    pullPolicy: IfNotPresent
containerPort: 80
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    path: /
healthcheck:
    path: /ping
    initialDelaySeconds: 5
    periodSeconds: 10
resources:
    requests:
        cpu: 250m
        memory: 256Mi
    limits:
        cpu: 500m
        memory: 512Mi
name: uploadservice
podAnnotations:
    cloudwatch.aws.com/include: 'true'
    sumologic.com/include: 'true'
