name: CI
on:
  push: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@master

      - name: build
        run: docker build -t alpine .

      - name: get sample
        run: git clone https://github.com/aidansteele/demo-serverless-aspnetcore.git

      - name: run
        uses: docker://alpine
        with:
          args: HelloWorld.sln
        #working-directory: demo-serverless-aspnetcore
