name: CI
on:
  push: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: chekcout
        uses: actions/checkout@master

      - name: build
        run: docker build -t alpine .

      - name: run
        uses: docker://alpine
        with:
          entrypoint: sh
          args: ["-c", "resharper-action testdata/inspect.xml"]
